version: '3'

services:
  mediawiki-1.43.0:
    image: mediawiki:latest
    deploy:
      replicas: 3
#      placement:
#        constraints:
#          - node.hostname == masterswarm
      resources:
        limits:
          cpus: "1"
          memory: "512M"
    restart: always
    ports:
      - 5546:80
    environment:
      MW_DB_HOST: ${MW_DB_HOST}
      MW_DB_NAME: ${MW_DB_NAME}
      MW_DB_USER: ${MW_DB_USER}
      MW_DB_PASSWORD: ${MW_DB_PASSWORD}
    volumes:
      - /mnt/nfs/shared/wiki/html:/var/www/html

volumes:
  images: