version: '3'
services:
  mediawiki:
    image: mediawiki:latest
    restart: always
    ports:
      - 5546:80
#    networks:
#      - wiki_net
    environment:
      MW_DB_HOST: ${MW_DB_HOST}
      MW_DB_NAME: ${MW_DB_NAME}
      MW_DB_USER: ${MW_DB_USER}
      MW_DB_PASSWORD: ${MW_DB_PASSWORD}
    volumes:
      - /mnt/nfs/shared/wiki/app:/var/www/html/images
      # Uncomment the following line after initial setup:
      # - ./LocalSettings.php:/var/www/html/LocalSettings.php

volumes:
  images:

#networks:
#  wiki_net:
#    external: true